Добавлено решение задачи 02-background-image из раздела 06-lection4
js-tasks-ru/htmlcss-20231222_erdman pull request #13
Opened 2024-02-02 09:02 UTC by Erdmans

2024-02-02 09:02 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-02-02 15:10 UTC, GSemikozov requested changes

2024-02-02 15:10 UTC, GSemikozov commented on 06-lection4/02-background-image/background-image.css
> +  @media (min-resolution: 2x) {
запрос внутри запроса? так делать не надо

2024-02-02 15:10 UTC, GSemikozov commented on 06-lection4/02-background-image/background-image.css
> +@media (min-width: 768px), (min-height: 432px) {
к высоте по задаче привязываться не надо, но можем и оставить

2024-02-02 15:50 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-02-02 16:16 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-02-02 16:20 UTC, Erdmans commented on 06-lection4/02-background-image/background-image.css
> +  @media (min-resolution: 2x) {
Исправлено

2024-02-02 16:27 UTC, Erdmans commented on 06-lection4/02-background-image/background-image.css
> +@media (min-width: 768px), (min-height: 432px) {
Давайте оставим, потому что, думаю, разрешение картинки также должно зависеть и от высоты. По крайней мере, если она занимает всё окно как обложка.

2024-02-03 06:18 UTC, GSemikozov approved these changes

2024-02-03 06:18 UTC, merged