Добавлен svg-спрайт
js-tasks-ru/htmlcss-20231222_erdman pull request #15
Opened 2024-02-03 21:17 UTC by Erdmans

2024-02-03 21:17 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-02-05 15:40 UTC, GSemikozov requested changes

2024-02-05 15:40 UTC, GSemikozov commented on assets/css/main.css
> +.svg-icon {
кроме самого спрайта надо еще использовать иконки из него в нашх компонентах)

2024-02-06 21:19 UTC, GSemikozov approved these changes

2024-02-06 21:19 UTC, merged