Добавлено решение задачи 01-button из раздела 03-lection1
js-tasks-ru/htmlcss-20231222_erdman pull request #4
Opened 2024-01-16 17:13 UTC by Erdmans

В main.css добавлен -webkit-font-smoothing: antialiased для того, чтобы отображение текста на Mac было идентично тому, что в Figma.

Также в переменные добавлены цвета, которые используются в Style Guide (но при этом заданы в нем без имени).

2024-01-16 17:13 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-01-16 21:17 UTC, GSemikozov requested changes

2024-01-16 21:17 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  font-size: 16px;
font-family не хватает

2024-01-16 21:17 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +button:disabled {
.button

2024-01-16 21:17 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  cursor: not-allowed;
pointer-events: none

2024-01-16 21:17 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +button:active:not(:disabled) {
лишнее

2024-01-16 21:17 UTC, GSemikozov commented on assets/css/main.css
>  * {
лучше сразу заменить `*` на body

2024-01-17 12:09 UTC, GSemikozov approved these changes

2024-01-17 12:10 UTC, merged