Добавлено решение задачи 01-histogram из раздела 04-lection2
js-tasks-ru/htmlcss-20231222_erdman pull request #6
Opened 2024-01-19 07:33 UTC by Erdmans

2024-01-19 07:34 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-01-19 12:52 UTC, GSemikozov requested changes

2024-01-19 12:52 UTC, GSemikozov commented on 04-lection2/01-histogram/index.html
> +      <article class="histogram">
просто div )

2024-01-25 21:38 UTC, GSemikozov approved these changes

2024-01-25 21:38 UTC, merged